<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'Causal\\ImageAutoresize\\' => array($typo3InstallDir . 'typo3conf/ext/image_autoresize/Classes'),
    'Emagineurs\\EMagineurs\\' => array($typo3InstallDir . 'typo3conf/ext/e_magineurs/Classes'),
    'Emagineurs\\EPackage\\' => array($typo3InstallDir . 'typo3conf/ext/e_package/Classes'),
    'Emagineurs\\EXcellent\\' => array($typo3InstallDir . 'typo3conf/ext/e_xcellent/Classes'),
    'Featdd\\DpnGlossary\\' => array($typo3InstallDir . 'typo3conf/ext/dpn_glossary/Classes'),
    'GeorgRinger\\News\\' => array($typo3InstallDir . 'typo3conf/ext/news/Classes'),
    'GridElementsTeam\\Gridelements\\' => array($typo3InstallDir . 'typo3conf/ext/gridelements/Classes'),
    'Helhum\\Typo3Console\\' => array($typo3InstallDir . 'typo3conf/ext/typo3_console/Classes/Console'),
    'In2code\\PowermailCond\\' => array($typo3InstallDir . 'typo3conf/ext/powermail_cond/Classes'),
    'In2code\\Powermail\\' => array($typo3InstallDir . 'typo3conf/ext/powermail/Classes'),
    'WapplerSystems\\WsScss\\' => array($typo3InstallDir . 'typo3conf/ext/ws_scss/Classes'),
);
